app/urls.py
from django.conf.urls import url
from . import views

app_name = 'app'
urlpatterns = [
    # post views
    #url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
]

app/models.py
from django.db import models
# imports for Post model
from django.utils import timezone
from django.contrib.auth.models import User

from django.urls import reverse

# define custom model manager to retrieve all posts with published status
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

# define Post model (basic model for blog posts)
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    # Field for post title. CharField translates to a varchar column in the SQL database.
    title = models.CharField(max_length=250)
    # This is a field intended to be used in URLs. A slug is a short label containing 
    # only letters, numbers, underscores or hyphens.
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # This field defines a many to one relationship. A user can write several posts.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # Body of the text. Translates to a text column in the sql database.
    body = models.TextField()
    # This date time indicates when the post was published.
    publish = models.DateTimeField(default=timezone.now)
    # This data time indicates when the post was created.
    created = models.DateTimeField(auto_now_add=True)
    # This date time indicates the last time the post was updated.
    updated = models.DateTimeField(auto_now=True)
    # Show the status of the post
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # the default manager
    published = PublishedManager() # the custom manager

    # contains meta data
    class Meta:
        # descending order is specified by the negative prefix
        ordering = ('-publish',)

    # string method is the human readable representation of the object
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('app:post_detail', args=[self.publish.year,
                                                self.publish.strftime('%m'),
                                                self.publish.strftime('%d'),
                                                self.slug])

# model for comments system
class Comment(models.Model):
    # each post might have multiple comments so we use a foreign key 
    # to connect a comment to a post, we name the relation as comments.
    # This is a many to one relationship.
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

app/forms.py
from django import forms
from .models import Comment

# we've inherited the base Form class
class EmailPostForm(forms.Form):
    # character field
    # each field has a default widget which decides how the field 
    # will be displayed in html
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    # comments field is optional
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail


def post_list(request, category=None):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'app/post/list.html', {'page': page,
                                                   'posts': posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'app/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'app/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'app/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

app/templates/app/base.html
<!-- tells django to load staticfiles template tags provided by
     the Django.contrib.staticfiles application  -->
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/app.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog.</p>
    </div>
</body>
</html>

app/templates/app/comment/create.html
{% extends "app/base.html" %}

{% block title %}New comment{% endblock %}

{% block content %}
    <h1>New comment for post "{{ post.title }}"</h1>
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add comment">
    </form>
{% endblock %}

app/templates/app/post/detail.html
{% extends "app/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}
    <!-- link to share post url -->
    <p><a href="{% url "app:post_share" post.id %}">Share this post</a></p>

    
    {% with comments.count as total_comments %}
        <!-- pluralize template filter is used to display comment/comments based on value of total_comments -->
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    
    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    
    
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {%  endif %}

{% endblock %}

app/templates/app/post/list.html
<!-- we tell django to inherit from base.html template -->
{% extends "app/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    <!-- iterate through posts -->
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        <!-- linebreaks converts output to html linebreaks -->
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}
{% endblock %}

app/templates/app/post/share.html
{% extends "app/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <h1>Share "{{ post.title }} by e-mail"</h1>
        <form action="." method="post">
            {{ form.as_p }}
            <!-- cross-site request forgery -->
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

app/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number}}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>